<a href="https://colab.research.google.com/github/0wenB/test-pytorch/blob/main/test_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

In [2]:
import torch
import numpy as np

**LISTS**

In [ ]:
my_lists = [1,2,3]
my_lists

[1, 2, 3]

**Numpy Array**

In [ ]:
np1 = np.random.rand(3,4)
np1

dtype('float64')

In [ ]:
np1.dtype

dtype('float64')

**TENSORS**

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
## create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0734, 0.8069, 0.4534, 0.6211],
        [0.2133, 0.6992, 0.4117, 0.1669],
        [0.4413, 0.7938, 0.5252, 0.7826]], dtype=torch.float64)

# **VID 3**

In [3]:
my_torch=torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#Reshape and review
my_torch=my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
# Reshape if we don't know the number of items using -1
my_torch2=torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
my_torch2=my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
my_torch3=torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
my_torch4=my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
#slices
my_torch7=torch.arange(10)
my_torch7


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
my_torch7[7] #Grab a specific item (this is not equivalent to number 7)

tensor(7)

In [13]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [15]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])